### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by InvisibleMalik** [Egsagon/neko-sama-api#2]
hey developer!
it was a great job done by you, working fine untill 2 days ago. suddenly showing this error while running main.py, please fix it ASAP.

thanks 
Output of the code:-
"> Enter query or URL: https://neko-sama.fr/anime/info/19196-ousama-ranking-yuuki-no-takarabako_vostfr
Selected anime: Ousama Ranking: Yuuki no Takarabako VOSTFR
> Set range start (default=0): 0
> Set range end (default=-1): 6
> Set path (default=tkinter): tkinter
Creating path tkinter
> Set request timeout (default=5): 5
Set backend (default=ffmpeg): ffmpeg
Downloading 6 episodes:
        * 0. ousama-ranking-yuuki-no-takarabako-01
        * 1. ousama-ranking-yuuki-no-takarabako-02
        * 2. ousama-ranking-yuuki-no-takarabako-03
        * 3. ousama-ranking-yuuki-no-takarabako-04
        * 4. ousama-ranking-yuuki-no-takarabako-05
        * 5. ousama-ranking-yuuki-no-takarabako-06
> Download ready. Press enter to continue.

=> Starting download!

* Downloading 1
[FRAG] Fetched provider best
Traceback (most recent call last):
  File "c:\Users\Malik Zahid\Downloads\Compressed\neko-sama-api-master_2_updated\neko-sama-api-master\main.py", line 71, in <module>    episode.download(path + str(episode.index) + '.mp4',
  File "C:\Users\Malik Zahid\AppData\Local\Programs\Python\Python311\Lib\site-packages\nekosama\core.py", line 263, in download     
    raw = self.get_fragments(provider, quality)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Malik Zahid\AppData\Local\Programs\Python\Python311\Lib\site-packages\nekosama\core.py", line 216, in get_fragments    res = re.findall(consts.re.m3u8, src)[0]
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range"

**Comment by Egsagon** [comment]
@InvisibleMalik Hi!

Thanks for pointing out this bug!
I guess it was due to an update on the website, they might have changed the way they obfusc the json file containing the M3U URL.

Anyway, this should be fixed new with https://github.com/Egsagon/neko-sama-api/commit/7a5424f56848905ece39f0811acaaaaf3c31c0c2.

**Comment by Egsagon** [comment]
Also closing this.
